### ISSUE TITLE
导出失败， 都是一个12.8kb损坏的zip文件

### ISSUE THREAD

**Issue by cnbattle** [lizheming/typecho-export-hugo#1]

**Comment by lizheming** [comment]
这个还不太好远程 debug。主要的逻辑都在这里 https://github.com/lizheming/typecho-export-hugo/blob/master/Action.php#L11-L80 你可以逐行打下日志看看有没有什么报错

**Comment by cnbattle** [comment]
找到原因了， docker php容器里 没有安装zip,  所有失败了，安装就可以了

**Comment by lizheming** [comment]
好的，给你点赞呀~
