### ISSUE TITLE
导出的zip文件在win和linux下都无法解压

### ISSUE THREAD

**Issue by seekdoor** [lizheming/typecho-export-hugo#2]
打开之后显示的都是`未知的文件格式`
![image](https://user-images.githubusercontent.com/6291329/110963664-4f5c2b80-838d-11eb-8cc7-3d06ddd80abd.png)

---
typecho版本（版本 1.0 (14.10.10)和版本 1.1 (17.10.30)）
php为5.6
mysql为5.6，数据库为utf8
vps已安装zip
![image](https://user-images.githubusercontent.com/6291329/110963872-8df1e600-838d-11eb-8c28-3878ced94d75.png)

---
尝试使用everedit打开文件
![image](https://user-images.githubusercontent.com/6291329/110964114-cc87a080-838d-11eb-845a-1ede15dd4e93.png)

**Comment by lizheming** [comment]
插件现在是调的命令行 zip 打的压缩包，你可以试试在 Linux 下用 unzip 解压是否OK

**Comment by seekdoor** [comment]
之前试过啦，并不行的欸。
![image](https://user-images.githubusercontent.com/6291329/110970263-88e46500-8394-11eb-9377-8f15fed9537d.png)
系统是ubuntu server 20.04LTS

**Comment by seekdoor** [comment]
能换成`tar`这个命令吗？应该更通用些吧，我看了一下`action.php`里面的`exec("cd $dir && zip -q -r $outputFile content");`这个临时改成tar命令的话该是啥啊。

**Comment by lizheming** [comment]
不行的话，你自己去机器上的 /tmp/Export2Hugo 目录下去取也行的

**Comment by seekdoor** [comment]
感谢老哥，已经到目录里下载下来啦。近几日刚把12到16年丢失的数据找回来，其他的在`https://web.archive.org/`上找的。现在准备和现有的数据合并了然后转hugo了。
再次感谢！

**Comment by lizheming** [comment]
嗯嗯，不客气，推荐一下我的 Hugo 教程在 vercel 上部署 hugo 超省心 https://imnerd.org/hugo-start.html
